# Generated by Django 4.0 on 2024-11-21 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kitty', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='kitty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoptions', to='Kitty.kitty'),
        ),
    ]
